# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Exprience
                                 A QGIS plugin
 Just a first plugin for some exprience
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-10-05
        copyright            : (C) 2019 by Prr21
        email                : Mr.gustav009@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Exprience class from file Exprience.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .prr import Exprience
    return Exprience(iface)
